drop table if exists todos;
drop table if exists groups;

CREATE TABLE groups(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50),
    group_order SMALLINT
);

CREATE TABLE todos (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   group_id INT,
   description VARCHAR(255),
   due DATE,
   created TIMESTAMP DEFAULT now(),
   completed BOOLEAN DEFAULT false,
   CONSTRAINT fk_group
       FOREIGN KEY (group_id)
       REFERENCES groups(id)
);

